music/urls.py
from django.urls import path, include
from .views import (DetailViewArtist, DetailViewAlbum, FavoriteViewSong, IndexViewArtist,
                    IndexViewAlbum, IndexViewSong, add_artist, DetailViewSong)
from django.views.generic import RedirectView

app_name = 'music'

url_artist = [
    path('', IndexViewArtist.as_view(), name='index_artist'),
    path('<int:pk>', DetailViewArtist.as_view(), name='detail_artist'),
    path('add', add_artist, name='add-artist')
]

url_album = [
    path('', IndexViewAlbum.as_view(), name='index_album'),
    path('<int:pk>', DetailViewAlbum.as_view(), name='detail_album'),
]

url_song = [
    path('', IndexViewSong.as_view(), name='index_song'),
    path('<int:pk>', DetailViewSong.as_view(), name='detail_song'),
]

urlpatterns = [
    path('', RedirectView.as_view(url='album/')),
    path('album/', include(url_album)),
    path('artist/', include(url_artist)),
    path('song/', include(url_song)),
    path('favorite/', FavoriteViewSong.as_view(), name='favorite_song'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='music')),
    path('music/', include('music.urls')),
    path('admin/', admin.site.urls),
    path('go-to-django/', RedirectView.as_view(url='https://djangoproject.com'), name='go-to-django'),
]

music/models.py
from django.db import models


class Artist(models.Model):
    name = models.CharField(max_length=50)
    photo = models.CharField(max_length=256)

    def __str__(self):
        return self.name


class Album(models.Model):
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    logo = models.CharField(max_length=256)
    genre = models.CharField(max_length=50)

    def __str__(self):
        return self.title


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    type = models.CharField(max_length=10)
    is_favorite = models.BooleanField()

    def __str__(self):
        return self.title

music/forms.py
from django import forms
from .models import Artist


class ArtistForm(forms.ModelForm):
    class Meta:
        mode = Artist
        fields = ['name', 'photo']

music/views.py
from music.models import Album, Artist, Song
from django.views.generic import ListView, DetailView, FormView, RedirectView
from django.shortcuts import render
from django.http.response import HttpResponseRedirect
from django.urls import reverse


app_name = 'music'


def add_artist(request):
    if request.POST:
        return HttpResponseRedirect(reverse('music:add-artist'))
    else:
        return render(request, 'music/add_artist.html')


class IndexViewAlbum(ListView):
    model = Album
    template_name = 'music/index_album.html'
    context_object_name = 'albums'


class DetailViewAlbum(DetailView):
    model = Album
    template_name = 'music/detail_album.html'
    context_object_name = 'album'


class IndexViewArtist(ListView):
    model = Artist
    template_name = 'music/index_artist.html'
    context_object_name = 'artists'


class DetailViewArtist(DetailView):
    model = Artist
    template_name = 'music/detail_artist.html'
    context_object_name = 'artist'


class FavoriteViewSong(ListView):
    template_name = 'music/favorite.html'
    context_object_name = 'favorite_songs'

    def get_queryset(self):
        return Song.objects.filter(is_favorite=True)


class IndexViewSong(ListView):
    model = Song
    template_name = 'music/index_song.html'
    context_object_name = 'songs'


class DetailViewSong(DetailView):
    model = Song
    template_name = 'music/detail_song.html'
    context_object_name = 'song'

music/templates/music/add_artist.html
{% extends 'music/base.html' %}
{% block body %}

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'music:add-artist' %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">
    </form>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
﻿
<head>
    <meta charset="UTF-8">
    <title> {% block title %}Sound cloud {% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="countainer-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle='collapse' data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index_album' %}">Music cloud</a>
        </div>
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'music:index_album' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
                        Albums
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'music:index_artist' %}">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;
                        Artists
                    </a>
                </li>
                <li class="active">
                    <a href="{% url 'music:index_song' %}">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;
                        Songs
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'music:favorite_song' %}">
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>&nbsp;
                        Favorite
                    </a>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url "music:add-artist" %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                        Add album
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                        Logout
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/detail_album.html
{% extends 'music/base.html' %}
{% block body %}
    <a href="{% url 'music:detail_artist' album.artist.id %}">
        <IMG src="{{ album.artist.photo }}" width="10%"><br>
        <label> {{ album.artist.name }}</label><br></a><br>
    <a href="{% url 'music:detail_album' album.artist.id %}">
        <IMG src="{{ album.logo }}" width="10%"><br>
        <label> {{ album.title }}</label><br></a><br>
    {% for song in album.song_set.all %}
        {{ song.title }} {{ song.type }} <!--{{ song.is_favorite }}--><br>
    {% endfor %}
{% endblock %}

music/templates/music/detail_artist.html
{% extends 'music/base.html' %}
{% block body %}
    <a href="{% url 'music:detail_artist' artist.id %}">
        <IMG src="{{ artist.photo }}" width="10%"><br>
        <label> {{ artist.name }}</label></a><br><br>
    {% for album in artist.album_set.all %}
        <a href="{% url 'music:detail_album' album.id %}">
            <IMG src="{{ album.logo }}" width="10%"><br>
            <label> {{ album.title }}</label></a><br><br>
    {% endfor %}
{% endblock %}

music/templates/music/detail_song.html
{% extends 'music/base.html' %}
{% block body %}
    <a href="{% url 'music:detail_artist' song.album.artist.id %}">{{ song.album.artist.name }}</a>
    <a href="{% url 'music:detail_album' song.album.id %}">{{ song.album.title }}</a> {{ song.title }}
    {{ song.type }}<br>
{% endblock %}

music/templates/music/favorite.html
{% extends 'music/base.html' %}
{% block body %}
    {% for song in favorite_songs %}
        <a href="{% url 'music:detail_artist' song.album.artist.id %}">{{ song.album.artist.name }}</a>
        <a href="{% url 'music:detail_album' song.album.id %}">{{ song.album.title }}</a> {{ song.title }}
        {{ song.type }}<br>
    {% endfor %}
{% endblock %}

music/templates/music/index_album.html
{% extends 'music/base.html' %}
{% block title %}Albums{% endblock %}
{% block body %}
    {% if albums %}
        All albums <br>
        {% for album in albums %}
            <a href="{% url 'music:detail_album' album.id %}"><img src="{{ album.logo }}"
                                                                   width="10%"><br> {{ album.title }}
            </a><br>
        {% endfor %}
    {% else %}
        You don`t have albums
    {% endif %}
{% endblock %}

music/templates/music/index_artist.html
{% extends 'music/base.html' %}

{% block body %}
    {% for artist in artists %}
        <a href="{% url 'music:detail_artist' artist.id %}">
            <IMG src="{{ artist.photo }}" width="10%"><br>
            <label> {{ artist.name }}</label></a><br><br>
    {% endfor %}
{% endblock %}

music/templates/music/index_song.html
{% extends 'music/base.html' %}
{% block title %}Songs{% endblock %}
{% block body %}
    {% for song in songs %}
        <a href="{% url 'music:detail_artist' song.album.artist.id %}">{{ song.album.artist.name }}</a>
        <a href="{% url 'music:detail_album' song.album.id %}">{{ song.album.title }}</a> {{ song.title }}
        {{ song.type }}<br>
    {% endfor %}
{% endblock %}